sudo: required
dist: trusty

env:
  - PYTHON=python2.7
  - PYTHON=python3.2

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq software-properties-common
  - sudo add-apt-repository -y ppa:vidplace7/bluez5
  - sudo apt-get update -qq
  - sudo apt-get -y install -qq bluez automake autoconf libglib2.0-dev libtool libgtk-3-dev libstartup-notification0-dev python-gi-dev libbluetooth-dev intltool python-dev python3-dev cython python-dbus python3-dbus dh-autoreconf
  - echo "Hi"
script:
  - ./autogen.sh
  - make
  - make check


